services:
  mongo:
    image: mongo:6
    container_name: chessmaster-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: chessmaster
    volumes:
      - mongodb_data:/data/db


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chessmaster-backend
    command: ["npm", "run", "start:dev"]  # Cambié esto para ejecutar el servidor
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app         # Monta tu código local en el contenedor
      - /usr/src/app/node_modules # Evita conflictos de dependencias

volumes:
  mongodb_data:
    driver: local
