services:
  mongo:
    image: mongo:6
    container_name: chessmaster-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: chessmaster
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chessmaster-backend
    command: ["npm", "run", "start:dev"] # Ejecuta en modo desarrollo
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      # Variables de entorno compartidas según el entorno
      NODE_ENV: ${NODE_ENV:-development} # Usa 'development' como valor por defecto si NODE_ENV no está definido
      MONGO_URI: ${MONGO_URI:-AZURE_COSMOS_CONNECTIONSTRING} # Valor por defecto para desarrollo
    restart: always
    volumes:
      - .:/usr/src/app # Monta tu código local en el contenedor
      - /usr/src/app/node_modules # Evita conflictos de dependencias

volumes:
  mongodb_data:
    driver: local
