services:
  mongo:
    image: mongo:6
    container_name: chessmaster-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: chessmaster
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin321
      MONGO_BIND_IP_ALL: "true"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chessmaster-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://admin:admin321@mongo:27017/chessmaster?authSource=admin
volumes:
  mongodb_data:
    driver: local
