name: CI/CD for Chessmaster Backend

on:
  push:
    branches:
      - main # Cambia "main" por la rama que uses como principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Login en Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login en el ACR
      - name: Docker Login to ACR
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      # Construir la imagen Docker
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/chessmaster-backend-nestjs:latest .

      # Subir la imagen al ACR
      - name: Push Docker Image to ACR
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/chessmaster-backend-nestjs:latest

      # Actualizar el Azure App Service para usar la nueva imagen
      - name: Update App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: chessmasterbackend
          images: ${{ secrets.ACR_LOGIN_SERVER }}/chessmaster-backend-nestjs:latest
